public enum Permissao {
    VER_SALDO,
    VER_LANCAMENTOS,
    ADICIONAR_RECEITA,
    ADICIONAR_DESPESA,
    EDITAR_LANCAMENTO,
    EXCLUIR_LANCAMENTO,
    GERENCIAR_CONTAS,
    GERENCIAR_METAS,
    GERENCIAR_MEMBROS,
    GERAR_RELATORIOS,
    CONFIGURAR_ORCAMENTO
}

